name: _quill_delta_suite_root
publish_to: none

environment:
  sdk: ^3.6.0

workspace:
  - packages/quill_delta_core
  - packages/quill_delta_html
  - packages/quill_delta_markdown
  - packages/quill_delta_pdf
  - packages/quill_delta_editor
  - packages/quill_delta_editor/example
