// ignore_for_file: experimental_member_use
//
// flutter_quill marks a handful of QuillSimpleToolbarConfig fields
// (`showClipboardCut/Copy/Paste`, `dialogTheme`, `iconTheme`) as
// `@experimental`. We forward them verbatim so the copyWith extension is
// fully drop-in for flutter_quill's API; consumers opting in accept the
// upstream experimental risk.
import 'package:flutter/widgets.dart';
import 'package:flutter_quill/flutter_quill.dart';

/// `copyWith` for [QuillSimpleToolbarConfig].
///
/// flutter_quill 11.5 ships [QuillSimpleToolbarConfig] without a `copyWith`,
/// which makes layered configuration ergonomically painful. This extension
/// fills that gap so callers (and the wrapper) can override a handful of
/// fields against a preset-built config without re-listing all ~40 properties.
extension QuillSimpleToolbarConfigCopyWithX on QuillSimpleToolbarConfig {
  QuillSimpleToolbarConfig copyWith({
    double? toolbarSectionSpacing,
    WrapAlignment? toolbarIconAlignment,
    WrapCrossAlignment? toolbarIconCrossAlignment,
    QuillSimpleToolbarButtonOptions? buttonOptions,
    List<QuillToolbarCustomButtonOptions>? customButtons,
    bool? multiRowsDisplay,
    bool? showDividers,
    bool? showFontFamily,
    bool? showFontSize,
    bool? showBoldButton,
    bool? showItalicButton,
    bool? showSmallButton,
    bool? showUnderLineButton,
    bool? showLineHeightButton,
    bool? showStrikeThrough,
    bool? showInlineCode,
    bool? showColorButton,
    bool? showBackgroundColorButton,
    bool? showClearFormat,
    bool? showAlignmentButtons,
    bool? showLeftAlignment,
    bool? showCenterAlignment,
    bool? showRightAlignment,
    bool? showJustifyAlignment,
    bool? showHeaderStyle,
    bool? showListNumbers,
    bool? showListBullets,
    bool? showListCheck,
    bool? showCodeBlock,
    bool? showQuote,
    bool? showIndent,
    bool? showLink,
    bool? showUndo,
    bool? showRedo,
    bool? showDirection,
    bool? showSearchButton,
    bool? showSubscript,
    bool? showSuperscript,
    bool? showClipboardCut,
    bool? showClipboardCopy,
    bool? showClipboardPaste,
    LinkStyleType? linkStyleType,
    HeaderStyleType? headerStyleType,
    Decoration? decoration,
    List<EmbedButtonBuilder>? embedButtons,
    LinkDialogAction? linkDialogAction,
    QuillDialogTheme? dialogTheme,
    QuillIconTheme? iconTheme,
    Axis? axis,
    Color? color,
    Color? sectionDividerColor,
    double? sectionDividerSpace,
    double? toolbarSize,
    double? toolbarRunSpacing,
  }) {
    return QuillSimpleToolbarConfig(
      toolbarSectionSpacing: toolbarSectionSpacing ?? this.toolbarSectionSpacing,
      toolbarIconAlignment: toolbarIconAlignment ?? this.toolbarIconAlignment,
      toolbarIconCrossAlignment: toolbarIconCrossAlignment ?? this.toolbarIconCrossAlignment,
      buttonOptions: buttonOptions ?? this.buttonOptions,
      customButtons: customButtons ?? this.customButtons,
      multiRowsDisplay: multiRowsDisplay ?? this.multiRowsDisplay,
      showDividers: showDividers ?? this.showDividers,
      showFontFamily: showFontFamily ?? this.showFontFamily,
      showFontSize: showFontSize ?? this.showFontSize,
      showBoldButton: showBoldButton ?? this.showBoldButton,
      showItalicButton: showItalicButton ?? this.showItalicButton,
      showSmallButton: showSmallButton ?? this.showSmallButton,
      showUnderLineButton: showUnderLineButton ?? this.showUnderLineButton,
      showLineHeightButton: showLineHeightButton ?? this.showLineHeightButton,
      showStrikeThrough: showStrikeThrough ?? this.showStrikeThrough,
      showInlineCode: showInlineCode ?? this.showInlineCode,
      showColorButton: showColorButton ?? this.showColorButton,
      showBackgroundColorButton: showBackgroundColorButton ?? this.showBackgroundColorButton,
      showClearFormat: showClearFormat ?? this.showClearFormat,
      showAlignmentButtons: showAlignmentButtons ?? this.showAlignmentButtons,
      showLeftAlignment: showLeftAlignment ?? this.showLeftAlignment,
      showCenterAlignment: showCenterAlignment ?? this.showCenterAlignment,
      showRightAlignment: showRightAlignment ?? this.showRightAlignment,
      showJustifyAlignment: showJustifyAlignment ?? this.showJustifyAlignment,
      showHeaderStyle: showHeaderStyle ?? this.showHeaderStyle,
      showListNumbers: showListNumbers ?? this.showListNumbers,
      showListBullets: showListBullets ?? this.showListBullets,
      showListCheck: showListCheck ?? this.showListCheck,
      showCodeBlock: showCodeBlock ?? this.showCodeBlock,
      showQuote: showQuote ?? this.showQuote,
      showIndent: showIndent ?? this.showIndent,
      showLink: showLink ?? this.showLink,
      showUndo: showUndo ?? this.showUndo,
      showRedo: showRedo ?? this.showRedo,
      showDirection: showDirection ?? this.showDirection,
      showSearchButton: showSearchButton ?? this.showSearchButton,
      showSubscript: showSubscript ?? this.showSubscript,
      showSuperscript: showSuperscript ?? this.showSuperscript,
      showClipboardCut: showClipboardCut ?? this.showClipboardCut,
      showClipboardCopy: showClipboardCopy ?? this.showClipboardCopy,
      showClipboardPaste: showClipboardPaste ?? this.showClipboardPaste,
      linkStyleType: linkStyleType ?? this.linkStyleType,
      headerStyleType: headerStyleType ?? this.headerStyleType,
      decoration: decoration ?? this.decoration,
      embedButtons: embedButtons ?? this.embedButtons,
      linkDialogAction: linkDialogAction ?? this.linkDialogAction,
      dialogTheme: dialogTheme ?? this.dialogTheme,
      iconTheme: iconTheme ?? this.iconTheme,
      axis: axis ?? this.axis,
      color: color ?? this.color,
      sectionDividerColor: sectionDividerColor ?? this.sectionDividerColor,
      sectionDividerSpace: sectionDividerSpace ?? this.sectionDividerSpace,
      toolbarSize: toolbarSize ?? this.toolbarSize,
      toolbarRunSpacing: toolbarRunSpacing ?? this.toolbarRunSpacing,
    );
  }
}
